-- DRAT uses URN identifiers (urn:drat:MimePartitioner), not integers, so this
-- is the string-id variant that workflow.sql documents as the alternative for
-- quoteFields. Generated from Mnemosyne's workflow.sql; do not edit by hand.
--
--  Licensed to the Apache Software Foundation (ASF) under one or more
--  contributor license agreements.  See the NOTICE file distributed with
--  this work for additional information regarding copyright ownership.
--  The ASF licenses this file to You under the Apache License, Version 2.0
--  (the "License"); you may not use this file except in compliance with
--  the License.  You may obtain a copy of the License at
--
--      http://www.apache.org/licenses/LICENSE-2.0
--
--  Unless required by applicable law or agreed to in writing, software
--  distributed under the License is distributed on an "AS IS" BASIS,
--  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--  See the License for the specific language governing permissions and
--  limitations under the License.

CREATE TABLE workflows
-- NOT NULL before PRIMARY KEY. The other order is rejected outright by
-- HSQLDB ("Unexpected token: NOT"), and a primary key is non-nullable by
-- definition in any case.
(workflow_id int NOT NULL PRIMARY KEY,
workflow_name varchar(255));

CREATE TABLE workflow_condition_map
(workflow_id int NOT NULL,
workflow_condition_id int NOT NULL);

CREATE TABLE event_workflow_map
(workflow_id int NOT NULL,
event_name varchar(255) NOT NULL);

CREATE TABLE workflow_tasks
(workflow_task_id varchar(255) NOT NULL PRIMARY KEY,
workflow_task_name varchar(255),
workflow_task_class varchar(255));

CREATE TABLE workflow_task_map
(workflow_id int NOT NULL,
workflow_task_id int NOT NULL,
task_order int NOT NULL);

-- workflow_instance_id is an identity column. It used to be a plain
-- "int PRIMARY KEY NOT NULL" with no DEFAULT, no IDENTITY and no
-- AUTO_INCREMENT, while DataSourceWorkflowInstanceRepository does not supply
-- one on the INSERT and then reads it back with MAX(workflow_instance_id) --
-- which is the giveaway that it expects the database to assign it. So every
-- instance was rejected with "Attempt to insert null into a non-nullable
-- column", and the workflow manager started cleanly, accepted a workflow
-- definition and then failed on the first instance.
--
-- Oracle deployments worked because workflow_oracle_create_sequences.sql
-- supplies a sequence and a trigger that populate the column. Every other
-- backend did not, and this is the schema a RADiX-generated project points
-- at.
CREATE TABLE workflow_instances
(workflow_instance_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
workflow_instance_status varchar(255),
workflow_id varchar(255) NOT NULL,
current_task_id varchar(255) NOT NULL,
start_date_time varchar(255),
end_date_time varchar(255),
current_task_start_date_time varchar(255),
current_task_end_date_time varchar(255),
priority float,
times_blocked int DEFAULT 0);

-- An alternative definition, for quoteFields -- string versions of
-- current_task_id and workflow_id. Commented out: it was live SQL creating a
-- table that the statement above had already created, so loading this file
-- failed on it. Swap it for the definition above if that is what you want.
--
-- CREATE TABLE workflow_instances
-- (workflow_instance_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
-- workflow_instance_status varchar(255),
-- workflow_id varchar(255) NOT NULL,
-- current_task_id varchar(255) NOT NULL,
-- start_date_time varchar(255),
-- end_date_time varchar(255),
-- current_task_start_date_time varchar(255),
-- current_task_end_date_time varchar(255),
-- priority float,
-- times_blocked int DEFAULT 0);

CREATE TABLE workflow_instance_metadata
(workflow_instance_id int NOT NULL,
workflow_met_key varchar(1000) NOT NULL,
workflow_met_val varchar(1000) NOT NULL);

CREATE TABLE workflow_conditions
(workflow_condition_id int NOT NULL PRIMARY KEY,
workflow_condition_name varchar(255) NOT NULL,
workflow_condition_class varchar(255) NOT NULL,
workflow_condition_timeout int,
workflow_optional boolean DEFAULT false);

CREATE TABLE  task_condition_map
(workflow_task_id int NOT NULL, 
-- The comma after this column was missing, so the statement did not parse.
workflow_condition_id int NOT NULL,
condition_order int NOT NULL);

CREATE TABLE workflow_task_configuration
(workflow_task_id int NOT NULL,
property_name varchar(1000) NOT NULL,
property_value varchar(1000) NOT NULL);

CREATE TABLE workflow_condition_configuration
(workflow_condition_id int NOT NULL,
property_name varchar(1000) NOT NULL,
property_value varchar(1000) NOT NULL);
