image: maven:3.9.9-eclipse-temurin-21

stages:
  - build
  - publish

cache:
  paths:
    - .m2/repository
    - target/

before_script:
  - apt-get update && curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
  - apt-get install -y nodejs

build_artifact:
  stage: build
  script:
     - mvn clean install -DskipTests
  artifacts:
    paths:
    - "distribution/target/dms-distribution-1.1-SNAPSHOT-bin.tar.gz"

publish_docker:
  stage: publish
  image: docker:1.11
  dependencies: 
    - build_artifact
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG} .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}
